### ISSUE TITLE
Point contact of wheel with the ground

### ISSUE THREAD

**Issue by padhupradheep** [rbdl/rbdl#1]
Hey! 

I'm trying to model a wheeled mobile robot using RBDL. I'm using the floating joint to model the mobile robot(similar to the humanoid robot). Maybe also I will try to use 3DoF joint, later. My question now mainly focuses on how to model the wheel and the ground contact? Should I just use the contact constraint and define the point where it should be touching the surface? Or is there anyother trick? 

Thanks!

**Comment by martinfelis** [comment]
Hi there,

RBDL gives you the tools to model a wide range of contact constraints. For a rolling ball without slipping in 3D you have to specify 3 constraints: one that restricts vertical movement and two to prevent slipping. I describe it with a bit more detail in my thesis which you can get from: https://archiv.ub.uni-heidelberg.de/volltextserver/19319/

Best regards!
