### ISSUE TITLE
sincos function is not supported by VS 2017

### ISSUE THREAD

**Issue by cbuchart** [rbdl/rbdl#23]
Compilation of Joint.cc in VS 2017 fails because it cannot find `sincos`.

**Comment by marcoalves20** [comment]
I have the same issue

**Comment by jeff-energid** [comment]
For a quick fix, I added this code to joint.cc (just to get a build working).
```
void sincos(double x, double* sinret, double* cosret)
{
	*sinret = sin(x);
	*cosret = cos(x);
}
```
