### ISSUE TITLE
Add integration to 📦 VCPKG

### ISSUE THREAD

**Issue by RDCH106** [rbdl/rbdl#24]
Add port for [VCPKG](https://github.com/microsoft/vcpkg) package management tool.

Current PR waiting for integration: https://github.com/microsoft/vcpkg/pull/13884

⚠️ If PR is accepted, the README must be updated

**Comment by RDCH106** [comment]
RBDL was included in VCPKG: https://github.com/microsoft/vcpkg/pull/13884#pullrequestreview-506244495

🎉🎉🎉

And it will be available for the next release.

**Comment by RDCH106** [comment]
⚠️⏳ Keep open this issue until the usage of the RBDL library with VCPKG will be documented in README

**Comment by martinfelis** [comment]
Hi, thanks for the contribution. This is really cool! 

Can you create a pull request for what exactly you would like to have in README? I have not yet used VCPKG so would greatly appreciate more specific details.

**Comment by RDCH106** [comment]
Sure!!

I will generate the specific documentation in the README in a PR when the next release of [vcpkg](https://github.com/microsoft/vcpkg) is ready.

It will improve the usability and distribution of the RBDL library. RBDL is prepared by vpkg using the release tags of this repository.
