### ISSUE TITLE
operator * undefind

### ISSUE THREAD

**Issue by areyougoodmalaysia** [rbdl/rbdl#30]
hello Martin;
l want to use your RBDL library on TWINCAT ----a soft real-time soft PLC system, so that i need to compile RBDL  to .lib static library.
So,I cant use Eigen and l use your simplemath library. this work may be no people do before.

After  l cmake RBDL with VS2019 on win10,there are some problem.

 operator * undefind；

and I find that there are three operator * in your class。

it seems that c++ allow only one operator overload in a class.

Im not very good in C++,so l hope get your reply.

**Comment by martinfelis** [comment]
Hi, can you please submit the full compiler output? Hard to tell where exactly stems from.
