### ISSUE TITLE
Boost errors when compiling with the URDF_READER add-on

### ISSUE THREAD

**Issue by alessandropalleschi** [rbdl/rbdl#31]
Hi, 
I am having some issues when compiling the library with the URDF_READER add-on.
Using the make command the following boost-related errors arise:

[ 71%] Built target rbdl
Scanning dependencies of target rbdl_urdfreader
[ 78%] Building CXX object addons/urdfreader/CMakeFiles/rbdl_urdfreader.dir/urdfreader.cc.o
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:15:9: error: ‘boost’ does not name a type; did you mean ‘bool’?
 typedef boost::shared_ptr<urdf::Link> LinkPtr;
         ^~~~~
         bool
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:16:15: error: ‘boost’ does not name a type; did you mean ‘bool’?
 typedef const boost::shared_ptr<const urdf::Link> ConstLinkPtr;
               ^~~~~
               bool
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:17:9: error: ‘boost’ does not name a type; did you mean ‘bool’?
 typedef boost::shared_ptr<urdf::Joint> JointPtr;
         ^~~~~
         bool
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:18:9: error: ‘boost’ does not name a type; did you mean ‘bool’?
 typedef boost::shared_ptr<urdf::ModelInterface> ModelPtr;
         ^~~~~
         bool
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:39:16: error: ‘LinkPtr’ was not declared in this scope
 typedef vector<LinkPtr> URDFLinkVector;
                ^~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:39:23: error: template argument 1 is invalid
 typedef vector<LinkPtr> URDFLinkVector;
                       ^
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:39:23: error: template argument 2 is invalid
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:40:16: error: ‘JointPtr’ was not declared in this scope
 typedef vector<JointPtr> URDFJointVector;
                ^~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:40:16: note: suggested alternative: ‘Joint’
 typedef vector<JointPtr> URDFJointVector;
                ^~~~~~~~
                Joint
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:40:24: error: template argument 1 is invalid
 typedef vector<JointPtr> URDFJointVector;
                        ^
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:40:24: error: template argument 2 is invalid
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:41:21: error: ‘LinkPtr’ was not declared in this scope
 typedef map<string, LinkPtr > URDFLinkMap;
                     ^~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:41:29: error: template argument 2 is invalid
 typedef map<string, LinkPtr > URDFLinkMap;
                             ^
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:41:29: error: template argument 4 is invalid
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:42:21: error: ‘JointPtr’ was not declared in this scope
 typedef map<string, JointPtr > URDFJointMap;
                     ^~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:42:21: note: suggested alternative: ‘Joint’
 typedef map<string, JointPtr > URDFJointMap;
                     ^~~~~~~~
                     Joint
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:42:30: error: template argument 2 is invalid
 typedef map<string, JointPtr > URDFJointMap;
                              ^
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:42:30: error: template argument 4 is invalid
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:44:42: error: ‘ModelPtr’ has not been declared
 bool construct_model (Model* rbdl_model, ModelPtr urdf_model, bool floating_base, bool verbose) {
                                          ^~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc: In function ‘bool RigidBodyDynamics::Addons::construct_model(RigidBodyDynamics::Model*, int, bool, bool)’:
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:45:3: error: ‘LinkPtr’ was not declared in this scope
   LinkPtr urdf_root_link;
   ^~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:48:24: error: base operand of ‘->’ is not a pointer
   link_map = urdf_model->links_;
                        ^~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:51:25: error: base operand of ‘->’ is not a pointer
   joint_map = urdf_model->joints_;
                         ^~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:56:17: error: type/value mismatch at argument 1 in template parameter list for ‘template<class _Tp, class _Sequence> class std::stack’
   stack<LinkPtr > link_stack;
                 ^
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:56:17: note:   expected a type, got ‘LinkPtr’
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:56:17: error: template argument 2 is invalid
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:61:14: error: request for member ‘push’ in ‘link_stack’, which is of non-class type ‘int’
   link_stack.push (link_map[(urdf_model->getRoot()->name)]);
              ^~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:61:40: error: base operand of ‘->’ is not a pointer
   link_stack.push (link_map[(urdf_model->getRoot()->name)]);
                                        ^~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:64:3: error: ‘ConstLinkPtr’ was not declared in this scope
   ConstLinkPtr& root = urdf_model->getRoot ();
   ^~~~~~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:64:3: note: suggested alternative: ‘ConstraintSet’
   ConstLinkPtr& root = urdf_model->getRoot ();
   ^~~~~~~~~~~~
   ConstraintSet
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:64:17: error: ‘root’ was not declared in this scope
   ConstLinkPtr& root = urdf_model->getRoot ();
                 ^~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:64:17: note: suggested alternative: ‘rint’
   ConstLinkPtr& root = urdf_model->getRoot ();
                 ^~~~
                 rint
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:64:34: error: base operand of ‘->’ is not a pointer
   ConstLinkPtr& root = urdf_model->getRoot ();
                                  ^~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:125:21: error: request for member ‘size’ in ‘link_stack’, which is of non-class type ‘int’
   while (link_stack.size() > 0) {
                     ^~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:126:13: error: expected ‘;’ before ‘cur_link’
     LinkPtr cur_link = link_stack.top();
             ^~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:131:21: error: ‘cur_link’ was not declared in this scope
     if (joint_idx < cur_link->child_joints.size()) {
                     ^~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:131:21: note: suggested alternative: ‘u_long’
     if (joint_idx < cur_link->child_joints.size()) {
                     ^~~~~~~~
                     u_long
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:132:7: error: ‘JointPtr’ was not declared in this scope
       JointPtr cur_joint = cur_link->child_joints[joint_idx];
       ^~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:132:7: note: suggested alternative: ‘Joint’
       JointPtr cur_joint = cur_link->child_joints[joint_idx];
       ^~~~~~~~
       Joint
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:138:18: error: request for member ‘push’ in ‘link_stack’, which is of non-class type ‘int’
       link_stack.push (link_map[cur_joint->child_link_name]);
                  ^~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:138:33: error: ‘cur_joint’ was not declared in this scope
       link_stack.push (link_map[cur_joint->child_link_name]);
                                 ^~~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:138:33: note: suggested alternative: ‘u_int’
       link_stack.push (link_map[cur_joint->child_link_name]);
                                 ^~~~~~~~~
                                 u_int
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:145:80: error: request for member ‘top’ in ‘link_stack’, which is of non-class type ‘int’
         cout << "joint '" << cur_joint->name << "' child link '" << link_stack.top()->name << "' type = " << cur_joint->type << endl;
                                                                                ^~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:150:18: error: request for member ‘pop’ in ‘link_stack’, which is of non-class type ‘int’
       link_stack.pop();
                  ^~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:157:5: error: ‘JointPtr’ was not declared in this scope
     JointPtr urdf_joint = joint_map[joint_names[j]];
     ^~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:157:5: note: suggested alternative: ‘Joint’
     JointPtr urdf_joint = joint_map[joint_names[j]];
     ^~~~~~~~
     Joint
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:158:13: error: expected ‘;’ before ‘urdf_parent’
     LinkPtr urdf_parent = link_map[urdf_joint->parent_link_name];
             ^~~~~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:159:13: error: expected ‘;’ before ‘urdf_child’
     LinkPtr urdf_child = link_map[urdf_joint->child_link_name];
             ^~~~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:164:45: error: ‘urdf_parent’ was not declared in this scope
     rbdl_parent_id = rbdl_model->GetBodyId (urdf_parent->name.c_str());
                                             ^~~~~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:164:45: note: suggested alternative: ‘urdf_model’
     rbdl_parent_id = rbdl_model->GetBodyId (urdf_parent->name.c_str());
                                             ^~~~~~~~~~~
                                             urdf_model
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:167:51: error: ‘urdf_joint’ was not declared in this scope
       cerr << "Error while processing joint '" << urdf_joint->name
                                                   ^~~~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:167:51: note: suggested alternative: ‘urdf_model’
       cerr << "Error while processing joint '" << urdf_joint->name
                                                   ^~~~~~~~~~
                                                   urdf_model
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:173:9: error: ‘urdf_joint’ was not declared in this scope
     if (urdf_joint->type == urdf::Joint::REVOLUTE || urdf_joint->type == urdf::Joint::CONTINUOUS) {
         ^~~~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:173:9: note: suggested alternative: ‘rbdl_joint’
     if (urdf_joint->type == urdf::Joint::REVOLUTE || urdf_joint->type == urdf::Joint::CONTINUOUS) {
         ^~~~~~~~~~
         rbdl_joint
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:209:5: error: ‘urdf_joint’ was not declared in this scope
     urdf_joint->parent_to_joint_origin_transform.rotation.getRPY (joint_rpy[0], joint_rpy[1], joint_rpy[2]);
     ^~~~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:209:5: note: suggested alternative: ‘rbdl_joint’
     urdf_joint->parent_to_joint_origin_transform.rotation.getRPY (joint_rpy[0], joint_rpy[1], joint_rpy[2]);
     ^~~~~~~~~~
     rbdl_joint
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:230:9: error: ‘urdf_child’ was not declared in this scope
     if (urdf_child->inertial) {
         ^~~~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:230:9: note: suggested alternative: ‘urdf_model’
     if (urdf_child->inertial) {
         ^~~~~~~~~~
         urdf_model
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:261:36: error: ‘urdf_child’ was not declared in this scope
       cout << "+ Adding Body: " << urdf_child->name << endl;
                                    ^~~~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:261:36: note: suggested alternative: ‘urdf_model’
       cout << "+ Adding Body: " << urdf_child->name << endl;
                                    ^~~~~~~~~~
                                    urdf_model
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:277:32: error: ‘urdf_child’ was not declared in this scope
       string trans_body_name = urdf_child->name + "_Translate";
                                ^~~~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:277:32: note: suggested alternative: ‘urdf_model’
       string trans_body_name = urdf_child->name + "_Translate";
                                ^~~~~~~~~~
                                urdf_model
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:283:85: error: ‘urdf_child’ was not declared in this scope
       rbdl_model->AddBody (rbdl_parent_id, rbdl_joint_frame, rbdl_joint, rbdl_body, urdf_child->name);
                                                                                     ^~~~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:283:85: note: suggested alternative: ‘urdf_model’
       rbdl_model->AddBody (rbdl_parent_id, rbdl_joint_frame, rbdl_joint, rbdl_body, urdf_child->name);
                                                                                     ^~~~~~~~~~
                                                                                     urdf_model
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc: In function ‘bool RigidBodyDynamics::Addons::URDFReadFromString(const char*, RigidBodyDynamics::Model*, bool, bool)’:
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:312:3: error: ‘ModelPtr’ was not declared in this scope
   ModelPtr urdf_model = urdf::parseURDF (model_xml_string);
   ^~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:312:3: note: suggested alternative: ‘Model’
   ModelPtr urdf_model = urdf::parseURDF (model_xml_string);
   ^~~~~~~~
   Model
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:314:32: error: ‘urdf_model’ was not declared in this scope
   if (!construct_model (model, urdf_model, floating_base, verbose)) {
                                ^~~~~~~~~~
/home/ale-cp/rbdl/addons/urdfreader/urdfreader.cc:314:32: note: suggested alternative: ‘model’
   if (!construct_model (model, urdf_model, floating_base, verbose)) {
                                ^~~~~~~~~~
                                model
addons/urdfreader/CMakeFiles/rbdl_urdfreader.dir/build.make:62: recipe for target 'addons/urdfreader/CMakeFiles/rbdl_urdfreader.dir/urdfreader.cc.o' failed
make[2]: *** [addons/urdfreader/CMakeFiles/rbdl_urdfreader.dir/urdfreader.cc.o] Error 1
CMakeFiles/Makefile2:664: recipe for target 'addons/urdfreader/CMakeFiles/rbdl_urdfreader.dir/all' failed
make[1]: *** [addons/urdfreader/CMakeFiles/rbdl_urdfreader.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

I am using Ubuntu 18.04, with Ubuntu 16.04 I am able to compile the everything without errors.
Do you have any idea how to fix this?

**Comment by graiola** [comment]
Hi, check PR #12

**Comment by ju6ge** [comment]
Closing after update to version 3.2.0
