### ISSUE TITLE
I want to realize the inverse kinematics of robot grasp  through the rbdl library,Can you give me method?

### ISSUE THREAD

**Issue by RIP4KOBE** [rbdl/rbdl#32]
I am currently researching the inverse kinematics of the grasp contact points to realize the robot grasping. I have get the position and orientation of grasp contact points, and now i  want to use the rbdl library to realize the inverse kinematics from the grasp contact points to the end of the gripper of the robot arm, so as to realize the robot grasping. Could anyone can tell me how to do that?

**Comment by martinfelis** [comment]
Please have a look at the function `InverseKinematics (Model &model, const Math::VectorNd &Qinit, InverseKinematicsConstraintSet &CS, Math::VectorNd &Qres)` defined in `Kinematics.h`. You can specify both position and orientation constraints in the `InverseKinematicsConstraintSet` and compute the inverse kinematics accordingly.
