### ISSUE TITLE
Build fails due to quaternion sqrt and sin

### ISSUE THREAD

**Issue by leemagnusson** [rbdl/rbdl#40]
It looks like std:: was recently removed from these functions. My compiler isn't so happy with that. It would be nice to keep those in.

**Comment by MrCCaesar** [comment]
I got the same problem and after adding std:: to these functions, I got other problems in  urdfreader.cc file like [https://gist.github.com/MrCCaesar/2aedff1825b3b7afe8c47a42967d1ad0](url)
