### ISSUE TITLE
Compile error on Ubuntu-20.04

### ISSUE THREAD

**Issue by ykk648** [rbdl/rbdl#43]
eigen3 and SimpleMath all fail

Consolidate compiler generated dependencies of target rbdl
[  7%] Building CXX object CMakeFiles/rbdl.dir/src/rbdl_version.cc.o
[ 15%] Building CXX object CMakeFiles/rbdl.dir/src/rbdl_mathutils.cc.o
In file included from /workspace/codes/rbdl-master/include/rbdl/rbdl_math.h:66,
                 from /workspace/codes/rbdl-master/include/rbdl/rbdl_mathutils.h:14,
                 from /workspace/codes/rbdl-master/src/rbdl_mathutils.cc:14:
/workspace/codes/rbdl-master/include/rbdl/Quaternion.h: In member function ‘RigidBodyDynamics::Math::Quaternion RigidBodyDynamics::Math::Quaternion::slerp(double, RigidBodyDynamics::Math::Quaternion) const’:
/workspace/codes/rbdl-master/include/rbdl/Quaternion.h:77:73: error: no matching function for call to ‘RigidBodyDynamics::Math::Quaternion::sqrt(double) const’
   77 |       double sin_half_theta = sqrt(1.0 - cos_half_theta * cos_half_theta);
      |                                                                         ^
In file included from /usr/include/eigen3/Eigen/Core:436,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /workspace/codes/rbdl-master/include/rbdl/rbdl_math.h:34,
                 from /workspace/codes/rbdl-master/include/rbdl/rbdl_mathutils.h:14,
                 from /workspace/codes/rbdl-master/src/rbdl_mathutils.cc:14:

**Comment by Cdfghglz** [comment]
Same here on 18.04

**Comment by ykk648** [comment]
@Cdfghglz  try [rbdl-orb](https://github.com/ORB-HD/rbdl-orb)

**Comment by Cdfghglz** [comment]
Thanks @ykk648 the orb one works.
