### ISSUE TITLE
New tag / release

### ISSUE THREAD

**Issue by briansoe66** [rbdl/rbdl#48]
Will there be any additional tag / release for rbdl?

@martinfelis , you stopped developing new features for rbdl a few years ago, correct? Do you now contribute to, or recommend, any of the following dynamic libraries that are more active: https://www.ieee-ras.org/model-based-optimization-for-robotics/resources/modeling-tools

**Comment by martinfelis** [comment]
At the moment there are not many new features that would warrant a new release. However the master branch should be safe to use if there is anything new you need.

> @martinfelis , you stopped developing new features for rbdl a few years ago, correct?

I guess I have to be honest with myself here, so yes indeed. I do see RBDL as a mature project that fulfills its goal in exposing dynamics and some kinematics algorithms. I personally have no plans for new features.

As for the other libraries I cannot comment on them as I have not used them.
