### ISSUE TITLE
"import rbdl"    error

### ISSUE THREAD

**Issue by Timkeeper2018** [rbdl/rbdl#52]
When I use `import rbdl `after building RBDL's Python API
I am prompted 
`python3.7/site-packages/rbdl-2.6.0-py3.7-linux-x86_64.egg/rbdl.cpython-37m-x86_64-linux -gnu.so: undefined symbol: _ZN17RigidBodyDynamics13ConstraintSet20AddContactConstraintEjRK9Vector3_tS3_PKcd`

How can I solve it please?
thanks a lot

**Comment by ju6ge** [comment]
I have not run into that, but I have been using `rbdl-orb` which has had many big updates. With #50 `rbdl` and `rbdl-orb` will be merged back together resulting in rbdl version `v3.2.0`. Can you test if that will work better for you?

**Comment by ju6ge** [comment]
Fixed with #50
