### ISSUE TITLE
Doxygen equations don't build: GPL Ghostscript 9.50: Unrecoverable error, exit code 1

### ISSUE THREAD

**Issue by mjhmilla** [rbdl/rbdl#57]
Is anyone else seeing this string of errors when they try to build the doxygen? For example:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1990   1   4   %oparray_pop   1989   1   4   %oparray_pop   1977   1   4   %oparray_pop   1833   1   4   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:
   --dict:731/1123(ro)(G)--   --dict:0/20(G)--   --dict:76/200(L)--   --dict:5/30(L)--   --dict:11/30(L)--
Current allocation mode is local
Current file position is 8386
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
Generating image form_4.png for formula
Error: /undefined in getenv
Operand stack:
   (outfile)

**Comment by ju6ge** [comment]
I have not noticed anything like that, does building the documentation fail for you?

I tried building the doc today and it seems to work for me …

**Comment by ju6ge** [comment]
The online documentation is now up to date 😘
