### ISSUE TITLE
module 'rbdl' has no attribute 'CalZeroMomentPoint'

### ISSUE THREAD

**Issue by TowoC** [rbdl/rbdl#58]
Hi,
I'm now using rbdl with python to implement human pose estimation.
While I need to calculate the zero point, I can not use the **rbdl.CalZeroMomentPoint**.
But I see there has this attribute in the source code.

Did there anything I miss to build when I am doing cmake?

![Screenshot from 2022-07-19 16-44-44 (2)](https://user-images.githubusercontent.com/55866531/179886445-4a7cc2db-c4c9-47f3-854a-ed8f79edc436.png)
![Screenshot from 2022-07-19 16-44-14 (2)](https://user-images.githubusercontent.com/55866531/179886450-9770478b-7027-4036-b7ff-c63f6a5a31ec.png)

Thanks a lot for replying.

**Comment by ju6ge** [comment]
Seems like the definition for that function is missing in the cython definitions. It should be fairly straight forward to add this. But I am quite constrained for time. If you need this it should be an easy addition to do yourself. Otherwise I will take a look when I have some time.

**Comment by ju6ge** [comment]
Just take a look at the python folder and the crbdl.pxd file ;)

**Comment by timchiu9781** [comment]
Thanks for your replying.
I will try to add that function.

**Comment by timchiu9781** [comment]
Hello ju6ge,
I have try to fixed the bug.
But it seems not only the cython definitions problem.
But also the calculation of CalZeroMomentPoint missed.

The CalZeroMomentPoint is only shown in rbdl_utils.h, and only define the variable there.
I found that most of the calculation are defined in rbdl_ptr_functions.h, and the CalZeroMomentPoint is not calculated there.
So I can't just add the definitions in cython to fixed it.

Maybe this bug only you can fixed it.
If you have the time, hope you can fix it. Thanks very much.

**Comment by timchiu9781** [comment]
I'm not sure that whether I add the CalZeroMomentPoint  function here is right or not. And also the variable defined here.
The variable all comes from rbdl_util.h
 
![Screenshot from 2022-07-22 18-28-34 (2)](https://user-images.githubusercontent.com/55866531/180421900-7dbce61d-3605-4254-8af9-baa985626748.png)

**Comment by ju6ge** [comment]
You might also need to add the function to rbdl-wrapper.pyx …

I have not touched that code in a while.

**Comment by timchiu9781** [comment]
Thanks a lot for your big help.
I have successfully add the function to rbdl-wrapper.pyx.
And also got another error, it seens I miss some definition in some code.
I've try to find out where it is, but I failed.

Do you know what happened to this error?
'CalcZeroMomentPoint' is not a member of 'RigidBodyDynamics'

**Comment by timchiu9781** [comment]
I found the problem and solve it successfully.
Now I can use the CalcZeroMomentPoint Func.
Really thanks for your help!

**Comment by ju6ge** [comment]
Great \o/ … If you have some time to open a pull request, I would be more than happy to review and include your fixes in the main repository ;)
