### ISSUE TITLE
 CMake Error at FindRBDL.cmake:245 (MESSAGE):     Could not find RBDL.  When running the 'simple' example

### ISSUE THREAD

**Issue by xiao-wang007** [rbdl/rbdl#76]
Hi 

Can someone help me to set the variable ```CUSTOM_RBDL_PATH``` in ``` FindRBDL.cmake```? 

source dir: ```/home/xiao/rbdl ```. build dir: ``` /home/xiao/rbdl-build ```. The build was successful and tested. I tried setting the ```CUSTOM_RBDL_PATH```in ccmake to these two dirs. Still not finding ``` RBDL```. 
What should I set it to, based on my case?

Please don't tell me there are tons of materials to read online. I know that.

Thanks in advance!

**Comment by ju6ge** [comment]
Duplicate #75
