### ISSUE TITLE
Fail to compile while use ROS_URDF_LIBRARY

### ISSUE THREAD

**Issue by whtqh** [rbdl/rbdl#85]
#1 typo?
https://github.com/rbdl/rbdl/blob/cbd9371ce822eeea1f0a880d57f71a4c60bc9b8a/addons/urdfreader/urdfreader.cc#L128C1-L128C1
```
#ifdef RBDL_USE_ROS_URDF_LIBRARY
  if (urdf_link->inertial) {
    auto I = urdf_link->inertial;
```
#2 pointer type
-  Body get_rbdl_body(const LinkPtr &urdf_link, bool is_root_link)
+ Body get_rbdl_body(const ConstLinkPtr &urdf_link, bool is_root_link)
```
rbdl/addons/urdfreader/urdfreader.cc:309:39: error: invalid initialization of reference of type ‘const LinkPtr&’ {aka ‘const std::shared_ptr<urdf::Link>&’} from expression of type ‘ConstLinkPtr’ {aka ‘std::shared_ptr<const urdf::Link>’}
  309 |   Body root_link_body = get_rbdl_body(root, true);

```
for the getRoot or getLink in `urdf_model/model.h` returns a `LinkConstSharedPtr`

**Comment by ju6ge** [comment]
I have no keept up to date with ROS_URDF. We had a pull request a while ago where some convenience functions where added to the RBDL parser. Might me that these bug creept in there. So I don't have a solution for you. If you find a fix, feel free to send a PR ;)
