### ISSUE TITLE
base link named as ''base_link'' for floating base robot error

### ISSUE THREAD

**Issue by xinsongyan** [rbdl/rbdl#9]
I just happened to test a robot with a its base link named as ''base_link''. 
When this robot has been loaded as a floating base robot, everything calculated are with repect to the robot base instead of the inertia base (world). Then I tried to change ''base_link'' to ''base'', everything works. I think another ''base_link'' is created as the world link name, it conflicts with the robot root link name.

**Comment by martinfelis** [comment]
The parser in 2.6.0 makes some unfortunate assumptions. Can you try the development version in the dev branch?

**Comment by martinfelis** [comment]
Hey @xinsongyan, does more recent code fix your issue?

**Comment by xinsongyan** [comment]
Hi, @martinfelis, I haven't tried yet. I used other name to avoid the problem. I will test it later.

**Comment by martinfelis** [comment]
Hey @xinsongyan, any updates on this?

**Comment by martinfelis** [comment]
@xinsongyan feel free to re-open should you still have an issue.
